---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
  tag: "tags"
baseurl: "/"
title: "NandoTech Blog"
canonifyurls: false
enableRobotsTXT: true
taxonomies:
  category: "categories"
  tag: "tags"
