---
contentdir: "content"
layoutdir: "layouts"
publishdir: "docs"
indexes:
  category: "categories"
  tag: "tags"
baseurl: "https://blog.nandotech.com/"
title: "NandoTech Blog"
canonifyurls: false
enableRobotsTXT: true
taxonomies:
  category: "categories"
  tag: "tags"
